In [1]:
import numpy as np

# Creating arrays 

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [11]:
[1,2,3,4,5]

[1, 2, 3, 4, 5]

In [13]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [14]:
a[2]

3

In [15]:
a[2] = 10

In [16]:
a

array([ 1,  2, 10,  4,  5])

In [21]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

# Multi-dementional arrays

In [24]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
n = np.array ([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
n[0 , 1]

2

In [29]:
n[0, 1] = 20

In [30]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [31]:
n[0]

array([ 1, 20,  3])

In [32]:
n[2] = [1,1,1]

In [33]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [34]:
# access to 2 columns 

n[:, 1]

array([20,  5,  1])

# Randomly generated arrays

In [47]:
# fixed the random seed. When you are executing it will be the same number
np.random.seed(5)
np.random.rand(5, 2)

array([[0.22199317, 0.87073231],
       [0.20671916, 0.91861091],
       [0.48841119, 0.61174386],
       [0.76590786, 0.51841799],
       [0.2968005 , 0.18772123]])

In [50]:
# random normal distribution

np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [51]:
# set certain arrays with low and high 
np.random.seed(2)
np.random.randint(low=0, high=100, size = (5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

# Element-wise operations

In [53]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [54]:
# add a number to array 

a + 1 

array([1, 2, 3, 4, 5])

In [55]:
# multiply 
a * 2

array([0, 2, 4, 6, 8])

In [56]:
b = (10 + (a*2)) **2 / 100

In [57]:
a + b 

array([1.  , 2.44, 3.96, 5.56, 7.24])

# Comparison operations

In [58]:
a

array([0, 1, 2, 3, 4])

In [59]:
# which elements of a >= 2 ?

a >= 2

array([False, False,  True,  True,  True])

In [64]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [61]:
# which elemtns of a > b? 
a > b 

array([False, False,  True,  True,  True])

In [ ]:
# which exactly elements of a > b

In [65]:
a

array([0, 1, 2, 3, 4])

In [66]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [67]:
a[a>b]

array([2, 3, 4])

# Summarizing operations 

In [68]:
a

array([0, 1, 2, 3, 4])

In [70]:
a.min()

0

In [71]:
a.max()

4

In [72]:
a.sum()

10

In [73]:
a.std()

1.4142135623730951

In [75]:
# Identity matrix

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [84]:
# Inverse matrix 

np.random.seed(2)
v = np.random.rand(3, 3)
v

array([[0.4359949 , 0.02592623, 0.54966248],
       [0.43532239, 0.4203678 , 0.33033482],
       [0.20464863, 0.61927097, 0.29965467]])

In [86]:
v_inv = np.linalg.inv(v)
v_inv

array([[-1.20936675,  5.11771977, -3.42333228],
       [-0.96691719,  0.279414  ,  1.46561347],
       [ 2.82418088, -4.07257903,  2.64627411]])