In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/home/timur/.local/lib/python3.8/site-packages/numpy/__init__.py'>

# Creating arrays 

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
np.full(5, 3)

array([3, 3, 3, 3, 3])

### Python list

In [11]:
[1,2,3,4,5]

[1, 2, 3, 4, 5]

### Switch to array

In [7]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

### Acces to 2rd element of our array

In [14]:
a[2]

3

### Replace 2rd element by new one

In [10]:
a[2] = 10

In [11]:
a

array([ 1,  2, 10,  4,  5])

### Create array with arange

from 3 to 10

In [21]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

from 0 to 10

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Create array with size 11 from o to 1

In [13]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

# Multi-dementional arrays

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

### Create 2 dimensional array with 5 rows and 2 columns

In [20]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6], 
    [7, 8, 9]
])

In [23]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Access to element from 0 row and 1 column

In [24]:
n[0 , 1]

2

### Assign new value

In [25]:
n[0, 1] = 20

In [26]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

### Acces to 0 row

In [27]:
n[0]

array([ 1, 20,  3])

### Access to 1 row

In [28]:
n[1]

array([4, 5, 6])

### Assign new row value. For example new value for 2nd row

In [29]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [30]:
n[2] = [1,1,1]

In [31]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

### Access to 2 columns 

In [32]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [33]:
n[:, 1]

array([20,  5,  1])

In [41]:
n[1]

array([4, 5, 6])

In [42]:
n[1,:]

array([4, 5, 6])

# Randomly generated arrays

### np.random.rand generate random array with 5 rows and 2 columns

In [47]:
# fixed the random seed. When you are executing it will be the same number
np.random.seed(5)
np.random.rand(5, 2)

array([[0.22199317, 0.87073231],
       [0.20671916, 0.91861091],
       [0.48841119, 0.61174386],
       [0.76590786, 0.51841799],
       [0.2968005 , 0.18772123]])

### random normal distribution

In [50]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

### set certain arrays with low, high and size 

In [51]:
np.random.seed(2)
np.random.randint(low=0, high=100, size = (5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

# Element-wise operations

In [43]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

### add a number to array 

In [44]:
a + 1 

array([1, 2, 3, 4, 5])

### multiply 

In [46]:
a * 2

array([0, 2, 4, 6, 8])

In [47]:
b = (10 + (a*2)) **2 / 100

In [48]:
a + b 

array([1.  , 2.44, 3.96, 5.56, 7.24])

# Comparison operations

In [49]:
a

array([0, 1, 2, 3, 4])

### which elements of a array >= 2 ?

In [59]:
a >= 2

array([False, False,  True,  True,  True])

In [51]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

### which elemtns of a > b? 

In [52]:
a > b 

array([False, False,  True,  True,  True])

### which exactly elements of a > b

In [53]:
a

array([0, 1, 2, 3, 4])

In [54]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [55]:
a[a>b]

array([2, 3, 4])

# Summarizing operations 

In [56]:
a

array([0, 1, 2, 3, 4])

In [57]:
a.min()

0

In [58]:
a.max()

4

In [59]:
a.sum()

10

In [60]:
a.std()

1.4142135623730951